name: Compile LaTeX document

on: [workflow_dispatch, push]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Github Action for LaTeX
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: main.tex
          working_directory: src
          docker_image: tianon/latex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf
